shinchan is a 5 year old boy . He is very naughty and very funny boy he make everybody laugh and irritates everyone........
mitsi is a 33 years old lady . she loves to do shopping alot and always run for the discount and she is very lazy..........
herry is a 35 years old man . he is alwasy busy at word and loves to party in sunday he will not wake up from bed..........
himawary is 0 years small girl . she loves jwels and very smart like her mother............................................